[versions]
android-buildTools = "34.0.0"
android-compileSdk = "34"
android-minSdk = "26"
android-targetSdk = "34"
androidx-activity = "1.8.2"
androidx-compose-compiler = "1.5.8"
androidx-hilt = "1.1.0"
androidx-lifecycle = "2.7.0"
androidx-navigation = "2.7.6"
androidx-test = "1.5.0"
androidx-testEspresso = "3.5.1"
androidx-workManager = "2.9.0"
coil = "2.5.0"
google-accompanist = "0.32.0"
google-dagger = "2.50"
google-glance-tooling = "0.2.2"
kotlin = "1.9.22"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.6.2"
plugin-android = "8.2.2"
plugin-dependencyUpdates = "0.51.0"
plugin-google-firebase-appDistribution = "4.0.1"
plugin-google-firebase-crashlytics = "2.9.9"
plugin-google-ksp = "1.9.22-1.0.17"
plugin-google-services = "4.4.0"
plugin-kotlinter = "4.2.0"
plugin-playPublisher = "3.8.6"
square-moshi = "1.15.0"
square-okhttp = "4.12.0"
square-retrofit = "2.9.0"
square-sqlDelight = "1.5.5"

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android" }
android-library = { id = "com.android.library", version.ref = "plugin-android" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-dagger" }
dependencyUpdates = { id = "com.github.ben-manes.versions", version.ref = "plugin-dependencyUpdates" }
google-firebase-appDistribution = { id = "com.google.firebase.appdistribution", version.ref = "plugin-google-firebase-appDistribution" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "plugin-google-firebase-crashlytics" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-google-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "plugin-google-services" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "plugin-kotlinter" }
playPublisher = { id = "com.github.triplet.play", version.ref = "plugin-playPublisher" }
square-sqldelight = { id = "com.squareup.sqldelight", version.ref = "square-sqlDelight" }

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-browser = "androidx.browser:browser:1.7.0"
androidx-collection = "androidx.collection:collection-ktx:1.4.0"
androidx-compose-bom = "androidx.compose:compose-bom:2023.10.01"
androidx-composeAnimation = { module = "androidx.compose.animation:animation" }
androidx-composeCompiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-composeFoundation = { module = "androidx.compose.foundation:foundation" }
androidx-composeMaterial3 = { module = "androidx.compose.material3:material3" }
androidx-composeMaterial3WindowSize = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-composeMaterialIcons = { module = "androidx.compose.material:material-icons-core" }
androidx-composeMaterialIconsExt = { module = "androidx.compose.material:material-icons-extended" }
androidx-composeRuntime = { module = "androidx.compose.runtime:runtime" }
androidx-composeUi = { module = "androidx.compose.ui:ui" }
androidx-composeUiGraphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-composeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-composeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-composeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-composeUiViewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-constraintlayoutCompose = "androidx.constraintlayout:constraintlayout-compose:1.0.1"
androidx-core = "androidx.core:core-ktx:1.12.0"
androidx-coreGoogleShortcuts = "androidx.core:core-google-shortcuts:1.1.0"
androidx-coreSplashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-coreTesting = "androidx.arch.core:core-testing:2.2.0"
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-glance-glanceAppwidget = "androidx.glance:glance-appwidget:1.0.0"
androidx-hiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hiltNav = { module = "androidx.hilt:hilt-navigation", version.ref = "androidx-hilt" }
androidx-hiltNavCompose = "androidx.hilt:hilt-navigation-compose:1.1.0"
androidx-hiltWork = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycleLivedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycleService = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-media = "androidx.media:media:1.7.0"
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidx-navigation" }
androidx-palette = "androidx.palette:palette-ktx:1.0.0"
androidx-testCore = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-testEspressoContrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-testEspresso" }
androidx-testEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-testEspresso" }
androidx-testExtJunit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-testExtTruth = { module = "androidx.test.ext:truth", version.ref = "androidx-test" }
androidx-testMonitor = "androidx.test:monitor:1.6.1"
androidx-testOrchestrator = "androidx.test:orchestrator:1.4.2"
androidx-testRules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-testRunner = "androidx.test:runner:1.5.2"
androidx-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
androidx-webkit = "androidx.webkit:webkit:1.10.0"
androidx-workRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-workManager" }
androidx-workTesting = { module = "androidx.work:work-testing", version.ref = "androidx-workManager" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
google-accompanistFlow = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "google-accompanist" }
google-accompanistInsetsUi = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "google-accompanist" }
google-accompanistNavigationMaterial = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "google-accompanist" }
google-accompanistPager = { module = "com.google.accompanist:accompanist-pager", version.ref = "google-accompanist" }
google-accompanistPagerInd = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "google-accompanist" }
google-accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "google-accompanist" }
google-accompanistSystemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "google-accompanist" }
google-dagger = { module = "com.google.dagger:dagger", version.ref = "google-dagger" }
google-daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "google-dagger" }
google-daggerHiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "google-dagger" }
google-daggerHiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "google-dagger" }
google-daggerHiltCore = { module = "com.google.dagger:hilt-core", version.ref = "google-dagger" }
google-daggerHiltTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "google-dagger" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-bom = "com.google.firebase:firebase-bom:32.7.1"
google-firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
google-glance-appwidgetHost = { module = "com.google.android.glance.tools:appwidget-host", version.ref = "google-glance-tooling" }
google-glance-appwidgetViewer = { module = "com.google.android.glance.tools:appwidget-viewer", version.ref = "google-glance-tooling" }
google-play-location = "com.google.android.gms:play-services-location:21.1.0"
google-play-maps = "com.google.android.gms:play-services-maps:18.2.0"
google-play-mapsKtx = "com.google.maps.android:maps-ktx:5.0.0"
inject = "javax.inject:javax.inject:1"
junit = "junit:junit:4.13.2"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesPlay = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-dagger-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "google-dagger" }
plugin-dependencyUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugin-dependencyUpdates" }
plugin-google-firebase-appDistribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "plugin-google-firebase-appDistribution" }
plugin-google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "plugin-google-firebase-crashlytics" }
plugin-google-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "plugin-google-ksp" }
plugin-google-services = { module = "com.google.gms:google-services", version.ref = "plugin-google-services" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-kotlinter = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "plugin-kotlinter" }
plugin-playPublisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "plugin-playPublisher" }
plugin-square-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "square-sqlDelight" }
robolectric = "org.robolectric:robolectric:4.11.1"
square-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.13"
square-moshi = { module = "com.squareup.moshi:moshi", version.ref = "square-moshi" }
square-moshiAdapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "square-moshi" }
square-moshiKotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "square-moshi" }
square-moshiKotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "square-moshi" }
square-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okhttp" }
square-okhttpBrotli = { module = "com.squareup.okhttp3:okhttp-brotli", version.ref = "square-okhttp" }
square-okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "square-okhttp" }
square-okhttpMockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "square-okhttp" }
square-okio = "com.squareup.okio:okio:3.7.0"
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit" }
square-retrofitConverterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "square-retrofit" }
square-sqlDelightAndroid = { module = "com.squareup.sqldelight:android-driver", version.ref = "square-sqlDelight" }
square-sqlDelightCoroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "square-sqlDelight" }
square-sqlDelightJvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "square-sqlDelight" }
square-turbine = "app.cash.turbine:turbine:1.0.0"

[bundles]
androidx-compose = ["androidx-composeAnimation", "androidx-composeFoundation", "androidx-composeMaterial3", "androidx-composeMaterial3WindowSize", "androidx-composeMaterialIcons", "androidx-composeMaterialIconsExt", "androidx-composeRuntime", "androidx-composeUi", "androidx-composeUiGraphics", "androidx-composeUiToolingPreview"]
coil = ["coil", "coilCompose"]
square-moshi = ["square-moshi", "square-moshiAdapters", "square-moshiKotlin"]
square-okhttp = ["square-okhttp", "square-okhttpLoggingInterceptor", "square-okhttpBrotli"]
square-retrofit = ["square-retrofit", "square-retrofitConverterMoshi"]
